version: '3.8'

services:
  llama-api-tor:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/arm64
    ports:
      - "5001:5000"
    tty: true
    stdin_open: true
    environment:
      - LLAMA_API_KEY=${LLAMA_API_KEY}
      - LLAMA_API_URL=${LLAMA_API_URL}
    volumes:
      - ../:/workspace
    restart: unless-stopped